---
functional:
  - Есть возможность создать батлы с другими игроками/ботом
  - Есть возможность создать аккаунт
non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
implicit:
  - По достижению отсчета в батле, батл завершается
  - Начисление победных очков(рейтинг)
